#!/usr/bin/perl -w

use strict;
use lib 'lib';

use Data::Dumper;
use Jemma::Import::Nmap;
use Jemma::Schema;
use Jemma::Utils;

my ($source) = 'nmap-172.17.17.0/24';
my ($x) = Jemma::Import::Nmap->new(name => $source);
my ($schema) = Jemma::Schema->connect('dbi:SQLite:data.sqlite');

$x->importdata('172.17.17.0/24');

$source = $schema->resultset('Source')->find_or_create( { name => $source })->id;

my $code = sub {
  for my $ip (keys %{$x->{data}}) {

    my $number = Jemma::Utils::ip_to_number($ip);
    $schema->resultset('Ip')->create( {
      start => $number,
      end   => $number,
      name  => $x->{data}{$ip},
      description => 'Something',
      source => $source,
    });
  }
};
$schema->txn_do($code);

