#!/usr/bin/perl -w

use strict;
use lib 'lib';

use Data::Dumper;
use Jemma::Import::Checkpoint;
use Jemma::Schema;
use Jemma;

my ($schema) = Jemma->schema;

my $code = sub {
  my ($source) = shift @ARGV;
  my ($x) = Jemma::Import::Checkpoint->new(name => $source);

  $x->importdata(
    $schema,
    $source,
    @ARGV,
  );
};
$schema->txn_do($code);
