#!/usr/bin/perl -w

use strict;
use lib 'lib';

use Data::Dumper;
use Jemma::Import::CiscoPIX;
use Jemma::Schema;
use Jemma;

my ($schema) = new Jemma->schema;
my $name = shift;

my $code = sub {
  for my $file (@ARGV) {
    my ($x) = Jemma::Import::CiscoPIX->new(name => $name);

    print "Importing $file\n";

    $x->importdata(
      $schema,
      $name,
      $file,
    );
  }
};
$schema->txn_do($code);
