#!/usr/bin/perl -w

use strict;
use lib 'lib';

use Data::Dumper;
use Jemma::Import::Checkpoint;
use Jemma::Schema;
use Jemma;

my ($schema) = Jemma->schema;

my $code = sub {
  for my $file (@ARGV) {
    my ($source) = 'Outerguard';
    my ($x) = Jemma::Import::Checkpoint->new(name => $source);

    print "Importing $file\n";

    $x->importdata(
      $schema,
      $source,
      $file,
    );
  }
};
$schema->txn_do($code);
